# What is Numpy? 
> is stands for Numerical Python. It's the foundational package for mathematical computing. Mathemetical and logical opetation on arrays. Operation related to linear algebra. Numpy has in-built functions for linear algebra and random number generation. ndarray is core object in NumPy.

## Basic ndarray:- 
> * Multidimensinal Array
* Homogeneous collection of values.
* Fast and efficient
* Support for mathematical functions
* Primary container for data exchange between python algorithms.

## Important attributes of an ndarray object are:
> * **ndarray.ndim:-** the number of axes(dimensions) of the array, the number of dimensions is referred to as rank.
* **ndarray.shape:-** the dimensions of the array. This is a tuple of integers indicating the size of the array in each dimension. For a matrix with n rows and m columns, shape will be (m,n)
* **ndarray.size:-** the total number of elements of the array. This is equal to product of the elements of the shape.
* **ndarray.dtype:-** an object describing the type of the elements in the array.

In [28]:
# Load numpy library:- 
import numpy as np

# How to create arrays in NumPy:- Create numpy array from Python List:- 
* We can create numpy arrays from regular Python list or tuples. Data type for resulting array is deduced from type of elements in the sequence.

In [29]:
# List to numpy array
lst = [5, 4, 3, 2, 1]
type(lst)
np_ar = np.array(lst)
type(np_ar)
np_ar


array([5, 4, 3, 2, 1])

In [30]:
# numpy matrix to numpy array
m = np.mat('1 2; 3 4; 5 6')
# m
np.array(m)

array([[1, 2],
       [3, 4],
       [5, 6]])

## Type casting:- 

In [37]:
lst = [1, 3, 5.0]
lst
np.array(lst)

array([1., 3., 5.])

## Type Precedence:- 
* bool
* Int
* Float
* String

In [46]:
# If you want to convert specific data type:- 
print(np.array(lst, dtype=float))
print(np.array(lst, dtype='U'))                    # Unicode - is type of String
print(np.array([1234, 678, 'Gopi'], dtype='<U2'))  # Unicdoe - is type of String also we can limit the character.

[1. 3. 5.]
['1' '3' '5.0']
['12' '67' 'Go']


# Available Data Types:- 

